name: Node.JS

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} with Node.JS v${{ matrix.version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [12.x, 14.x]

    steps:
      - name: Install Node.JS v${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v2

      - name: Log versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: npm run build --if-present

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          github.repository == 'danielsolartech/next-database' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true

      - name: Publish
        if: |
          github.repository == 'danielsolartech/next-database' &&
          startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}